### ISSUE TITLE
How to access rawMarkdownBody?

### ISSUE THREAD

**Issue by vnugent** [LekoArts/gatsby-themes#333]
I want to add an editor to my blog based on the minimal starter.

I'm struggling to find a way to get the raw markdown (`rawMarkdownBody` in gatsby blog starter).
to feed it to the editor. 

Or is there a way to reverse the mdx object in `post.body`?

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

Since the `MdxPost` type implements the generic `Post` interface and `MdxPost` is a child of the normal `Mdx` node you can query it by doing a query on the `parent`.

```graphql
query YourRawMDQuery {
  post {
    description
    title
    body
    ... on MdxPost {
      id
      parent {
        ... on Mdx {
          id
          rawBody
        }
      }
    }
  }
}
```

Or as a picture:

![image](https://user-images.githubusercontent.com/16143594/78147359-afcfb280-7433-11ea-83c9-2644a9466535.png)
