### ISSUE TITLE
[gatsby-theme-minimal-blog] How to add another Blog style page

### ISSUE THREAD

**Issue by Jigar3** [LekoArts/gatsby-themes#370]
## Summary
So I want to create an additional Link in the Navbar, which will be similar to blogs like I want to create a new list of write-ups which are not blogs and have them display the same way as blogs,

Navbar will look like this
![image](https://user-images.githubusercontent.com/32068121/80305899-7b0a0d80-87dd-11ea-8941-52198140c3ee.png)

And want the podcast summaries to be displayed like this
![image](https://user-images.githubusercontent.com/32068121/80305923-9117ce00-87dd-11ea-8937-c70d6372f5a7.png)

Please help me to achieve this

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

I can't give you a step-by-step solution to this but can you give you a rough outline of what you'll need to do.

- Add a new `gatsby-source-filesystem` entry to your own gatsby-config.js so that you can read in the podcasts, like here: https://github.com/LekoArts/gatsby-themes/blob/master/themes/gatsby-theme-minimal-blog-core/gatsby-config.js#L9-L14

- The blog overview you want to mimic lives here: https://github.com/LekoArts/gatsby-themes/blob/master/themes/gatsby-theme-minimal-blog/src/components/blog.tsx. So you could create a file at `src/pages/podcast-summaries.js` and copy the file initially. You'll need to switch out the relative imports to imports from the npm package `@lekoarts/gatsby-theme-minimal-blog`. You need to add a GraphQL query that queries the MDX files with a filter on `sourceInstanceName` for the name you have given  for the `gatsby-source-filesystem` entry.

- Source that data from the GraphQL query into the Listing component in the right shape that it expects it. Or use a modified version of the Listing component.

Hope that helps, please let me know. Closing this as answered :)

**Comment by Jigar3** [comment]
> So you could create a file at src/pages/podcast-summaries.js and copy the file initially. 

Didn't understand this? Could you be a little specific here :grimacing: @LekoArts
