### ISSUE TITLE
How can I change the site name in the header to a Logo?

### ISSUE THREAD

**Issue by mattmaker** [LekoArts/gatsby-themes#386]
I am using the Minimal Blog theme and I want to change the site name in the header to a logo instead.

What would be the recommended way to do this?

I tried adding siteLogo with the path for the image into Gatsby-config.js and use that in the header.tsx component, but the image doesn't display on the site.

**Comment by LekoArts** [comment]
Thanks for the issue!

I merged #390 in so that one can more easily shadow the header contents. (Published in `@lekoarts/gatsby-theme-minimal-blog@2.3.3`).

You can shadow this file now to change the title to e.g. a logo:
https://github.com/LekoArts/gatsby-themes/blob/master/themes/gatsby-theme-minimal-blog/src/components/header-title.tsx
