### ISSUE TITLE
How to add fieldData to created node

### ISSUE THREAD

**Issue by SOHELAHMED7** [LekoArts/gatsby-themes#387]
## Summary

How to add fieldData to already created node?

https://github.com/LekoArts/gatsby-themes/blob/1be7b53e4ab5b466478de4118c4b62eeb47af4f8/themes/gatsby-theme-minimal-blog-core/gatsby-node.js#L242-L258

Above code shows new node for MdxPage is created. There the field data is `title` and `slug`. I want to add more field data there for e.g. 

```js
const fieldData = {
      title: node.frontmatter.title,
      slug: node.frontmatter.slug,
      other_data: node.frontmatter.other_data,
    }
```
How can I achieve this? I searched a lot about Gatsby Node API but did not get perfect solution

## My attempt 

In my project's gatsby-node.js I tried creating new nodes and I got the solution but it is not perfect and very long reduntant I think

Here `other_data` is `title_2` and I created a new  node `MdxPage23`

```js

  createTypes(`
    interface Page @nodeInterface {
      id: ID!
      slug: String!
      title: String!
      excerpt(pruneLength: Int = 160): String!
      body: String!
    }

    interface Page2 @nodeInterface {
      id: ID!
      slug: String!
      title: String!
      title_2: String!
      excerpt(pruneLength: Int = 160): String!
      body: String!
    }

    type MdxPage implements Node & Page2 {
      slug: String!
      title: String!
      title_2: String!
      excerpt(pruneLength: Int = 140): String! @mdxpassthrough(fieldName: "excerpt")
      body: String! @mdxpassthrough(fieldName: "body")
    }
  `);
};



exports.onCreateNode = (
  { node, actions, getNode, createNodeId, createContentDigest },
  themeOptions
) => {
  const { createNode, createParentChildLink, createNodeField } = actions;

  const { postsPath, pagesPath } = withDefaults(themeOptions);

  // Make sure that it's an MDX node
  if (node.internal.type !== `Mdx`) {
    return;
  }

  // Create a source field
  // And grab the sourceInstanceName to differentiate the different sources
  // In this case "postsPath" and "pagesPath"
  const fileNode = getNode(node.parent);
  const source = fileNode.sourceInstanceName;


  // Check for "pages" and create the "Page" type
  if (node.internal.type === `Mdx` && source === pagesPath) {
    const fieldData = {
      title: node.frontmatter.title,
      title_2: node.frontmatter.title_2,
      slug: node.frontmatter.slug,
    };

    const mdxPageId = createNodeId(`${node.id} >>> MdxPage22`);

    createNode({
      ...fieldData,
      // Required fields
      id: mdxPageId,
      parent: node.id,
      children: [],
      internal: {
        type: `MdxPage33`,
        contentDigest: createContentDigest(fieldData),
        content: JSON.stringify(fieldData),
        description: `Mdx implementation of the Page interface`,
      },
    });

    const node_h = getNode(mdxPageId);

    createParentChildLink({ parent: node, child: getNode(mdxPageId) });
  }
};

```

### Theme

minimal-blog theme (https://minimal-blog.lekoarts.de/)

### Environment (if relevant)

```
  System:
    OS: Linux 4.15 Ubuntu 18 
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 11.14.0 - ~/.nvm/versions/node/v11.14.0/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v11.14.0/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.129
    Firefox: 75.0
  npmPackages:
    gatsby: ^2.13.3 => 2.20.22
    gatsby-plugin-google-analytics: ^2.1.4 => 2.2.2
    gatsby-plugin-manifest: ^2.2.3 => 2.3.3
    gatsby-plugin-netlify: ^2.1.3 => 2.2.1
    gatsby-plugin-offline: ^2.2.4 => 2.2.10
    gatsby-plugin-sitemap: ^2.2.19 => 2.3.2
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.8 => 1.1.8
  npmGlobalPackages:
    gatsby-cli: 2.12.0
```

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: Yes. provided above
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A 

Feel free to ask more info if needed

**Comment by MartinDevillers** [comment]
I'm trying to accomplish the same thing! I want to add a few custom fields to my page's frontmatter and then use these fields in components like `page.tsx` to do some custom rendering. Somehow I (naively) assumed that any frontmatter key-value-pair would be automagically mapped to the `PageProps` object, but I fear things are not that easy. My Googling lead me down the same path as you creating a custom `gatsby-node.js` and trying to wire everything together in `onCreateNode` and `createResolvers`, but I haven't had much luck (plus I'm not so fond of adopting all this boilerplate into my project). Eagerly awaiting feedback :-)

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

In practice this is easy to achieve but I can totally understand that this isn't straightforward, so no worries :)

I cloned https://github.com/LekoArts/gatsby-starter-minimal-blog and added a subtitle to the frontmatter of `about.mdx` inside `content/pages/about`:

```md
---
title: About
slug: "/about"
subtitle: "The subtitle goes here"
---
```

For the `Page` type these lines are important:

https://github.com/LekoArts/gatsby-themes/blob/6b5f08a040dbe196697d187367163f11558a43fa/themes/gatsby-theme-minimal-blog-core/gatsby-node.js#L243-L259

What they say in easier terms (top to bottom):

- Create a unique node id (a node is the smallest unit of Gatsby's data store and needs to be unique) with the `node.id` from `Mdx`. The latter is created with `gatsby-plugin-mdx`
- Create a new node (with `createNode`) that takes in the field data from `Mdx` and spreads them into the root level (that's why you can query e.g. the title at the root and not `frontmatter.title`). Name this node with the type `MdxPage`
- Create a Parent => Child relationship link between the new `MdxPage` node and the parent `Mdx` node
- As in the schema customization step it says `type MdxPage implements Node & Page` the  `MdxPage` is now also accessible under `Page`

In practice this means:

![image](https://user-images.githubusercontent.com/16143594/80862226-9bb9e380-8c73-11ea-89f0-cce81c9f8e94.png)

As the `MdxPage` is a child of `Page` you can directly query the union `... on MdxPage`. This more specific type also has access to the parent `Mdx`. This contains the new frontmatter I added.

Then you'll need to shadow the file that contains the query of `Page` and the component itself. **Important:** You need to use the `.tsx` extension (you don't have to write TypeScript).

You can see the changes here: https://github.com/LekoArts/minimal-blog-additional-field/commit/4d7a6da8c4d0191eff3ababfdb2466016ea751dd

Et voilá, the subtitle appeared:

![image](https://user-images.githubusercontent.com/16143594/80862858-809da280-8c78-11ea-9f85-bd2e86e4b07e.png)

Hope that helps! :)

**Comment by SOHELAHMED7** [comment]
Amazing. Thanks very much. That explanation of `node.id` and `createNode` is very explanatory. I was not able to completely understand it before; but now I can.

If you have some  useful links to learn even more about this -> `createNode`, parent in GraphQL queries, please feel free to share

**Comment by MartinDevillers** [comment]
Hero! Works exactly as advertised and thank you so much for taking the time to explain these concepts. For newbies like myself it's not always clear where Gatsby ends and MDX begins. Your excellent explanations help a lot.

For other readers, please note that the shadowed files reside in different packages :
 
*   `src/@lekoarts/gatsby-theme-minimal-blog/components/page.tsx`
*  `src/@lekoarts/gatsby-theme-minimal-blog`**`-core`**`/templates/page-query.tsx`

**Comment by LekoArts** [comment]
Found an even better way to access/set that data: https://github.com/LekoArts/gatsby-themes/issues/438
