### ISSUE TITLE
Cara-theme Layout overlapping in mobile

### ISSUE THREAD

**Issue by py563** [LekoArts/gatsby-themes#405]
When in portrait mode on mobile, on safari, brave (tested on only two for now) if text content in more in about us section it overlaps with projects section and similarly contact us. If in landscape mode the whole theme overlaps on each other, can be tested on the cara demo site.

**Comment by Chizzah** [comment]
Not something he feels like fixing it seems. I'll see what I can do and let you know. Liking this cara theme. Maybe I'll just do it over though. This shadow business is new to me.

https://github.com/LekoArts/gatsby-themes/issues/279

**Comment by AtiqGauri** [comment]
@py563  @Chizzah  Hey can you help me build this cara theme successfully.. please

I have executed these command successfully without any error:
```
gatsby new cara LekoArts/gatsby-starter-portfolio-cara
gatsby develop
gatsby build
```
I did change my name in intro.mdx folder

The static site (inside public folder) is blank when opened in browser or when pushed on github pages.

I want to build it showcase my portfolio on github page...

What am I doing wrong??

**Comment by py563** [comment]
Hi Atiq
, 
Can you give more information on my twitter and keybase same as my GitHub handle, the above information not helpful. This is not a discussion forum or something for general help,  it is a issue tracker. If you believe the issue you are facing is generic error please create a new issue with all logs. Else please do ping me, i will try my best to help. 

Thanks

**Comment by LekoArts** [comment]
Hi!

As mentioned in https://github.com/LekoArts/gatsby-themes/issues/279 you'll need to adapt the `factor` for your pages if the content is longer than the defaults I set. This is the limitation of the parallax effect and something the user of the theme will need to adapt. As also pointed out in the other issue I don't intend on fixing the view on landscape mode. If you feel strongly about this you could probably change this via CSS.

@AtiqGauri Please open own issues in the future (https://github.com/LekoArts/gatsby-themes/issues/411) instead of writing in another unrelated one. Thanks!

Hope that answer clears some things up!
