### ISSUE TITLE
Editing path for posts

### ISSUE THREAD

**Issue by artt** [LekoArts/gatsby-themes#428]
## Summary
Wondering how I could make the URL for posts to look like `www.<address>/2020/06/name-of-post`.

## Relevant information
I'm quite new to Gatsby. I followed the [tutorial](https://www.gatsbyjs.org/tutorial/) and was able to edit path that would lead to blog posts (in `gatsby-node.js` > `.onCreateNode`) like so:

```js
exports.onCreateNode = ({ node, getNode, actions }) => {
  const { createNodeField } = actions
  if (node.internal.type === `MarkdownRemark`) {
    const slug = createFilePath({ node, getNode, basePath: `pages` })
    createNodeField({
      node,
      name: `slug`,
      // I imagine you could query more stuff and add, for example, year, here
      value: `/blog` + slug,
    })
  }
}
```

Using a theme is very perplexing for me. I guess I need to shadow the `gatsby-node.js` file (of the `minimal-blog-core` theme), but I'm not sure how to do that. I'd like to be able to set it so the path to a blog post becomes something like, `www.<address>/<YYYY>/<MM>/name-of-post`.

I realize I can customize the slug in the `mdx` file, but I'd like for it to be done automatically.

To be more general, my questions are
1. How do I shadow `gatsby-node.js` of a theme?
2. If a theme I'm using is using another theme (`-core`), can I (and how do I) shadow `core`'s files?

Thanks a lot for your help, and for @LekoArts for a great theme!

### Theme

[`minimal-blog`](https://github.com/LekoArts/gatsby-themes/tree/master/themes/gatsby-theme-minimal-blog)

**Comment by LekoArts** [comment]
Hi, thanks for the issue! That was an interesting problem to solve :)

> I'm quite new to Gatsby. I followed the tutorial and was able to edit path that would lead to blog posts (in gatsby-node.js > .onCreateNode) like so:

This is a valid approach when you also control the `createPages` lifecycle. But since the theme controls that you  can't pipe the created slug into the page creation process.

> How do I shadow gatsby-node.js of a theme?

At the moment you can't do that.

> If a theme I'm using is using another theme (-core), can I (and how do I) shadow core's files?

The regular shadowing works with multiple themes, so creating files at `<root>/src/theme-core/`

---

Your problem was solvable by customizing the `slug` field on the `Post` interface (and `MdxPost` type). You see, [here](https://github.com/LekoArts/gatsby-themes/blob/d62857ffd1d2d97cfa31cb6ca37cb39db48467d0/themes/gatsby-theme-minimal-blog-core/gatsby-node.js#L73) and [here](https://github.com/LekoArts/gatsby-themes/blob/d62857ffd1d2d97cfa31cb6ca37cb39db48467d0/themes/gatsby-theme-minimal-blog-core/gatsby-node.js#L99) the `slug` gets defined by the field extension called `slugify`:

https://github.com/LekoArts/gatsby-themes/blob/d62857ffd1d2d97cfa31cb6ca37cb39db48467d0/themes/gatsby-theme-minimal-blog-core/gatsby-node.js#L43-L56

You can override/fix field types in your site (documentation: https://www.gatsbyjs.org/docs/schema-customization/#fixing-field-types).

Create a `gatsby-node.js` file in your project with the following contents:

```js
const kebabCase = require(`lodash.kebabcase`)

exports.createSchemaCustomization = ({ actions }) => {
  const { createTypes, createFieldExtension } = actions

  const customSlug = (source) => {
    const title = kebabCase(source.title)
    const date = new Date(source.date)
    const year = date.getUTCFullYear()
    const month = date.getUTCMonth() + 1
    const slug = source.slug ? source.slug : `${year}/${month}/${title}`

    return `/${slug}`.replace(/\/\/+/g, `/`)
  }

  createFieldExtension({
    name: `customSlug`,
    extend() {
      return {
        resolve: customSlug,
      }
    },
  })

  createTypes(`
    interface Post @nodeInterface {
      slug: String! @customSlug
    }
    
    type MdxPost implements Node & Post {
      slug: String! @customSlug
    }
  `)
}
```

- You can import `kebabCase` because it's a dependency of the `-core` theme
- You create a new field extension called `customSlug` that uses the function with the same name
- This function receives `source` which looks like this:

```js
{
  slug: undefined,
  title: 'Introduction to "Defence against the Dark Arts"',
  date: '2019-11-07T00:00:00.000Z',
  tags: [
    { name: 'Tutorial', slug: 'tutorial' },
    { name: 'Dark Arts', slug: 'dark-arts' }
  ],
  banner: './defence-against-the-dark-arts.jpg',
  description: 'Defence Against the Dark Arts (abbreviated as DADA) is a subject taught at Hogwarts School of Witchcraft and Wizardry and Ilvermorny School of Witchcraft and Wizardry. In this class, students study and learn how to defend themselves aga
inst all aspects of the Dark Arts, including dark creatures, curses, hexes and jinxes (dark charms), and duelling.',
  id: '51ab8259-4dc5-562b-aa52-2dee0de256d3',
  parent: 'a2a529ac-5184-5652-a26e-a3e58d941c67',
  children: [],
  internal: {
    type: 'MdxPost',
    contentDigest: 'b46fa5f2b708e2900175ee849305ee53',
    content: '{"title":"Introduction to \\"Defence against the Dark Arts\\"","date":"2019-11-07T00:00:00.000Z","tags":[{"name":"Tutorial","slug":"tutorial"},{"name":"Dark Arts","slug":"dark-arts"}],"banner":"./defence-against-the-dark-arts.jpg","descri
ption":"Defence Against the Dark Arts (abbreviated as DADA) is a subject taught at Hogwarts School of Witchcraft and Wizardry and Ilvermorny School of Witchcraft and Wizardry. In this class, students study and learn how to defend themselves against all
 aspects of the Dark Arts, including dark creatures, curses, hexes and jinxes (dark charms), and duelling."}',
    description: 'Mdx implementation of the Post interface',
    counter: 70,
    owner: '@lekoarts/gatsby-theme-minimal-blog-core'
  },
  __gatsby_resolved: { slug: '/introductionTo"DefenceAgainstTheDarkArts"' }
}
```

- Therefore you can extract the `source.date` to form a custom slug

The creation of the final slug are these two lines:

```js
const slug = source.slug ? source.slug : `${year}/${month}/${title}`
return `/${slug}`.replace(/\/\/+/g, `/`)
```

If `slug` is given in the fronmatter, use that. If not, create it.
This will give the following result (as one post has `slug` in the frontmatter):

![image](https://user-images.githubusercontent.com/16143594/86366298-e8716900-bc7a-11ea-92bd-f6cc30876670.png)

**Comment by SOHELAHMED7** [comment]
@LekoArts 

Thanks for the explanation.

Question (not related to this issue):

When we edit `gatsby-config.js` and `gatsby-node.js` file we need to restart dev server by `$ gatsby develop` and it takes significant amount of time like for e.g. 30 sec to 90 sec . I am almost sure that this step is mandatory and there is no alternative to this, but is there still any way that we can have experience like **edit**, **save** and **refresh** (like hot module replacement or PHP) and no need to restart dev server?
