### ISSUE TITLE
[minimal-blog]: Add option to prefix blog posts

### ISSUE THREAD

**Issue by LekoArts** [LekoArts/gatsby-themes#512]
## Summary

This shouldn't be necessary: https://sohelahmed.site/blog/adding-blog-in-url-in-gatsby-theme-minimal-blog-by-leko-arts

Let's expose an option to prefix blog posts.

---

Necessary follow-up (for some breaking changes across all themes):

Unify naming on those options for paths and expose the options for every page creation. But let's first add changesets to have better changelogs for the breaking changes.

**Comment by SOHELAHMED7** [comment]
It seems like there is a mistake. Please feel free to correct me if I am wrong.

You have added `postsPrefix` to pages creation code in gatsby-node.js instead of posts creation code 

https://github.com/LekoArts/gatsby-themes/blob/master/themes/gatsby-theme-minimal-blog-core/gatsby-node.js#L310-L333

**Comment by LekoArts** [comment]
whoops, misread that. Fixed in:

```
Successfully published:
 - @lekoarts/gatsby-theme-minimal-blog-core@2.6.2
 - @lekoarts/gatsby-theme-minimal-blog@2.7.2
```

**Comment by SOHELAHMED7** [comment]
✔️ Edited my blog which recommends to upgrade to 2.7.2
