### ISSUE TITLE
Minimal Blog Theme Pagination Help

### ISSUE THREAD

**Issue by erayusta** [LekoArts/gatsby-themes#539]
Hello,

I want to add pagination to minimal theme but i have no any idea. Do you have any solution suggestions? 

PS: I am a newbie to gatsby theme

**Comment by LekoArts** [comment]
Hi!

I fear that is not a trivial change and especially if you're a beginner to Gatsby I don't think it's an easy task to achieve.

Roughly, you'll want to follow these steps:

1) Use the `onCreatePage` API to delete the created `/blog` page
2) Use the `createPages` API (and maybe this guide: https://www.gatsbyjs.com/docs/adding-pagination/) to recreate the just now deleted `/blog` page. In order to achieve the same look you need to import the wrapping components (e.g. Layout) like in the template for it: https://github.com/LekoArts/gatsby-themes/blob/master/themes/gatsby-theme-minimal-blog/src/components/blog.tsx

Step 2 is definitely the more involved step. You'll want to query the allPost type (not allMarkdownRemark like in the tutorial).

Hope that helps!
