### ISSUE TITLE
[minimal-blog]: Incorrect rendering of bottom section

### ISSUE THREAD

**Issue by alberto-lanfranco** [LekoArts/gatsby-themes#726]
## Description

I'm currently experimenting with the minimal-blog theme. More precisely I'm editing the bottom section: `src/@lekoarts/gatsby-theme-minimal-blog/texts/bottom.mdx` 
I noticed two problems:

1.  Non-link text is visibly smaller than link text
2. Markdown footnotes are not rendered

### Steps to reproduce

Edit the bottom section:
`src/@lekoarts/gatsby-theme-minimal-blog/texts/bottom.mdx`

Paste the following text into the file:

```
<Title text="Test" />

non-link part of the text, [versus link part](www.emample.com) [^1]
[^1]: Note: this is a footer that should be rendered at the bottom of this section

More specifically, it should be rendered below this text also.
```

Here's a a live demo of the built website: [link](https://618671665873a000084f248a--blissful-goldberg-a122cf.netlify.app)

### Expected result

The text should have uniform size regardless of being a link or not.
The footnote should be rendered correctly at the end of the section.

### Actual result

Link text is bigger than regular text. Footnote is not rendered properly.

### Environment

Can't run `gatsby info --clipboard` because I'm building this website on Netlify.

**Comment by LekoArts** [comment]
Hi, thanks for the issue! I've put up https://github.com/LekoArts/gatsby-themes/pull/729 to fix the link issue.

It'll then look like this:

![image](https://user-images.githubusercontent.com/16143594/141677597-7f16e25f-235f-4fd4-b55f-3b2bd1da3d4b.png)

The footnotes are bigger because I edited the Theme UI config with

```js
  section_bottom: {
    ".footnotes": {
      li: {
        fontSize: 4,
      },
    },
  },
```

So if you want to change styles of that section you can use the `section_bottom` variant.

You're using footnotes incorrectly by the way :) The need to be at the end of the doc:
https://www.markdownguide.org/extended-syntax/#footnotes
